#run this deployment workflow if there is a change in the client directory upon a commit
name: deploy-client 

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t umukorog2/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag umukorog2/client umukorog2/dockerhub
      - run: docker push umukorog2/dockerhub      
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save a1f7173e-1877-47d5-9d16-80380cc322f5
      - run: kubectl rollout restart deployment client-depl #restart the deployment
      
    
