#run this deployment workflow if there is a change in the auth directory upon a commit
name: deploy-manifests 

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save b7dcbe45-0cbe-48f9-b952-beca0c26105e
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
    
