#run this deployment workflow if there is a change in the auth directory upon a commit
name: deploy-manifests 

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save a1f7173e-1877-47d5-9d16-80380cc322f5
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
    
