#run this deployment workflow if there is a change in the expiration directory upon a commit
name: deploy-expiration 

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t umukorog2/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag umukorog2/expiration umukorog2/expiration
      - run: docker push umukorog2/expiration      
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save b7dcbe45-0cbe-48f9-b952-beca0c26105e
      - run: kubectl rollout restart deployment expiration-depl #restart the deployment
      
    
